import streamlit as st
from PIL import Image
from gemini_helper import get_gemini_response
import base64

st.set_page_config(
    page_title="AI NutriCare",
    layout="wide"
)

def add_bg_from_local(image_file):
    with open(image_file, "rb") as f:
        encoded_string = base64.b64encode(f.read()).decode()
    



st.markdown("""
<div style="
background: linear-gradient(
    rgba(0,0,0,0.55),
    rgba(0,0,0,0.55)
),
url('https://images.unsplash.com/photo-1498837167922-ddd27525d352');
background-size: cover;
background-position: center;
padding: 25px;
border-radius: 16px;
color: white;
text-align: center;
margin-bottom: 25px;">
<h2 style="margin-bottom: 8px;">🥗 AI NutriCare</h2>
<p style="font-size: 14px; opacity: 0.9;">
Smart calorie & nutrition insights
</p>
</div>
""", unsafe_allow_html=True)

st.image(
    "static/food_bg.jpg",
    caption="🍽️ Balanced meal example",
    use_container_width=True
)


input_prompt = """
You are a certified nutritionist and registered dietitian with experience in food image analysis,
Indian and international cuisines, and evidence-based nutrition science.

Your task is to analyze the uploaded food image and provide an accurate, cautious,
and user-friendly nutritional assessment.

ANALYSIS GUIDELINES (STRICT):
- Identify ONLY food items that are clearly visible in the image.
- Do NOT assume hidden ingredients, cooking methods, or portion sizes.
- If the cuisine is unclear, state that explicitly.
- Prefer Indian portion standards (katori, roti size, ladle, plate) when applicable.
- Use standard nutritional databases for estimation.
- If image quality or angle limits accuracy, clearly mention it.
- Avoid overconfidence; be precise but cautious.

FOR EACH IDENTIFIED FOOD ITEM, PROVIDE:
- Food name
- Estimated calories (kcal)
- Macronutrients:
  • Carbohydrates (g)
  • Protein (g)
  • Fat (g)

AFTER ITEM-WISE ANALYSIS, PROVIDE:
1. Total estimated calories of the meal
2. Overall nutritional balance assessment
3. Health classification:
   - Healthy
   - Moderately Healthy
   - Unhealthy
4. Short reasoning (2–3 clear lines)
5. One realistic improvement suggestion (practical, not extreme)
6. Confidence score (0–100%) indicating estimation reliability

OUTPUT FORMAT (STRICT — DO NOT CHANGE):

Item 1:
- Name:
- Calories:
- Carbohydrates:
- Protein:
- Fat:

Item 2:
- Name:
- Calories:
- Carbohydrates:
- Protein:
- Fat:

Total Calories:
Nutrition Balance:
Health Classification:
Reasoning:
Improvement Suggestion:
Confidence Score:

Medical Disclaimer:
This analysis is generated by an AI model for informational purposes only.
It is not a substitute for professional medical or dietary advice.
Please consult a qualified healthcare professional or registered dietitian
for personalized recommendations.
"""

def input_image_setup(uploaded_file):
    if uploaded_file is not None:
        return [{
            "mime_type": uploaded_file.type,
            "data": uploaded_file.getvalue()
        }]
    return None

st.header(" ⬆️Upload Image")
st.write("Upload a food image to get calorie & nutrition insights")

uploaded_file = st.file_uploader(
    "📸 Upload food image",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file:
    image = Image.open(uploaded_file)
    st.image(image,
use_container_width=True)

    submit = st.button("🔍 Analyze Calories")

    if submit:
        image_data = input_image_setup(uploaded_file)

        with st.spinner("Analyzing food..."):
            response = get_gemini_response(input_prompt, image_data)

        st.subheader("🔎 Analysis")
        st.write(response)




















